### ISSUE TITLE
Build failing on create

### ISSUE THREAD

**Issue by paulsheldrake** [pantheon-systems/terminus-build-tools-plugin#123]
When running this command [from the docs](https://pantheon.io/docs/guides/build-tools/create-project/)
`terminus build:project:create d8 pantheon-d8-composer-project`
The build process will fail

```
[notice] Enabled on-server development via SFTP for "dev"
PHP Fatal error:  Uncaught Error: Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument() in /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php:1228
Stack trace:
#0 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1124): Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->escapeArgument('paul.sheldrake@...')
#1 [internal function]: Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->Pantheon\TerminusBuildTools\Commands\{closure}('paul.sheldrake@...')
#2 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1124): array_map(Object(Closure), Array)
#3 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1108): Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->runCommandTemplateOnRemoteEnv('brain-1st.dev', Array, 'Install site', Array)
#4 /Users/paulsheldrake/.terminus/plugins/terminus-build-t in /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php on line 1228

Fatal error: Uncaught Error: Call to undefined method Symfony\Component\Process\ProcessUtils::escapeArgument() in /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php:1228
Stack trace:
#0 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1124): Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->escapeArgument('paul.sheldrake@...')
#1 [internal function]: Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->Pantheon\TerminusBuildTools\Commands\{closure}('paul.sheldrake@...')
#2 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1124): array_map(Object(Closure), Array)
#3 /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php(1108): Pantheon\TerminusBuildTools\Commands\BuildToolsCommand->runCommandTemplateOnRemoteEnv('brain-1st.dev', Array, 'Install site', Array)
#4 /Users/paulsheldrake/.terminus/plugins/terminus-build-t in /Users/paulsheldrake/.terminus/plugins/terminus-build-tools-plugin/src/Commands/BuildToolsCommand.php on line 1228
```

**Comment by greg-1-anderson** [comment]
This is fixed in dev-master of Terminus. We need a stable tag.

Duplicate issue: https://github.com/pantheon-systems/terminus/issues/1808
