### ISSUE TITLE
Terminus build Error: sed: -e expression #1, char 1: Unknown command: ``'''

### ISSUE THREAD

**Issue by aaronlsilber** [pantheon-systems/terminus-build-tools-plugin#196]
I'm trying to build a project ala;

```
terminus build:project:create --org=myorg --team='My Organization' d8 myproject -vvvv
```

and shortly after it creates the repository on Github, it errors out with;

```
[notice] Creating repository myorg/myproject
 [notice] Call GitHub API: POST orgs/myorg/repos
 [notice] Executing git init
sed: -e expression #1, char 1: Unknown command: ``'''
 [CompletionWrapper]  Command `git init` failed with exit code 1 
 [CompletionWrapper]  Exit code 1 
PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Users\aaron.silber\AppData\Local\Temp\loc9FA.tmp\myproject\vendor\drupal\coder\.git\objects\pack\pack-4975f183e5bc913ad4dfa8ac16f4f97171e3c416.pack": unlink(C:\Users\aaron.silber\AppData\Local\Temp\loc9FA.tmp\myproject\vendor\drupal\coder\.git\objects\pack\pack-4975f183e5bc913ad4dfa8ac16f4f97171e3c416.pack): Permission denied. in C:\Users\aaron.silber\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php:184
Stack trace:
#0 C:\Users\aaron.silber\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\Users\aaron.silber\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 C:\Users\aaron.silber\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php(178): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 C:\Users\aaron.silber\AppData\Roa in C:\Users\aaron.silber\AppData\Roaming\Composer\vendor\symfony\filesystem\Filesystem.php on line 184
```

The build tool actually does create the repo on Github.

Any thoughts on how to fix this?

I'm on Windows 10 — which I imagine has a 50% likelihood of contributing to the issue. ;)

**Comment by greg-1-anderson** [comment]
Build Tools is completely untested on Windows. There are a number of Windows-related Terminus bugs that are blockers for us to start on Windows support for build tools. Most Windows users run Build Tools via a Linux virtual machine to get around this limitation.

**Comment by aaronlsilber** [comment]
Thanks @greg-1-anderson! This is helpful. I'll try Windows Subsystem for Linux.
