### ISSUE TITLE
Fatal error: Uncaught Error: Call to a member function getName() on null

### ISSUE THREAD

**Issue by kyletaylored** [pantheon-systems/terminus-build-tools-plugin#439]
Running the `build:env:create` produces the Fatal Error.

```bash
terminus build:env:create dunder-d8-alpha intg

PHP Notice:  Trying to get property 'id' of non-object in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php on line 64

Notice: Trying to get property 'id' of non-object in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php on line 64
PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php:69
Stack trace:
#0 [internal function]: Pantheon\TerminusBuildTools\Commands\EnvCreateCommand->createBuildEnv('dunder-d8-alpha', 'intg', Array)
#1 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\An in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php on line 69

Fatal error: Uncaught Error: Call to a member function getName() on null in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php:69
Stack trace:
#0 [internal function]: Pantheon\TerminusBuildTools\Commands\EnvCreateCommand->createBuildEnv('dunder-d8-alpha', 'intg', Array)
#1 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#2 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#3 /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\An in /Users/kyletaylor/.terminus/terminus-dependencies-617a5343ca/vendor/pantheon-systems/terminus-build-tools-plugin/src/Commands/EnvCreateCommand.php on line 69
```

**Comment by kyletaylored** [comment]
Seems to error out both on site name and site UUID.

**Comment by kporras07** [comment]
@kyletaylored have you tried `terminus build:env:create dunder-d8-alpha.dev intg`? The source  env should be site_name.site_env

**Comment by kyletaylored** [comment]
Ah, that seemed to do it. Also I had some mixed usage between Terminus 2/3 plugins until I reset and migrated the plugins. Thanks!
