### ISSUE TITLE
Unable to spinup D9 - FATAL Error

### ISSUE THREAD

**Issue by jahzlariosa** [pantheon-systems/terminus-build-tools-plugin#445]
Current version: 3.0.7

Command: terminus build:project:create --git=github --team='My Agency Name' d9 my-site

Error

```PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Style\SymfonyStyle::writeBuffer() must be of the type string, null given, called in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php on line 397 and defined in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php:460
Stack trace:
#0 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php(397): Symfony\Component\Console\Style\SymfonyStyle->writeBuffer(NULL, false, 1)
#1 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/pantheon-systems/terminus-build-tools-plugin/src/Credentials/CredentialManager.php(244): Symfony\Component\Console\Style\SymfonyStyle->write(Array)
#2 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/pantheon-systems/terminus-build-tools-plugin/src/Credentials/CredentialManager.php(214): Pantheon\TerminusBuildTools\Cre in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php on line 460

Fatal error: Uncaught TypeError: Argument 1 passed to Symfony\Component\Console\Style\SymfonyStyle::writeBuffer() must be of the type string, null given, called in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php on line 397 and defined in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php:460
Stack trace:
#0 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php(397): Symfony\Component\Console\Style\SymfonyStyle->writeBuffer(NULL, false, 1)
#1 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/pantheon-systems/terminus-build-tools-plugin/src/Credentials/CredentialManager.php(244): Symfony\Component\Console\Style\SymfonyStyle->write(Array)
#2 /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/pantheon-systems/terminus-build-tools-plugin/src/Credentials/CredentialManager.php(214): Pantheon\TerminusBuildTools\Cre in /Users/josephlariosa/.terminus/terminus-dependencies-4f7bf5e1bb/vendor/symfony/console/Style/SymfonyStyle.php on line 460```

**Comment by jahzlariosa** [comment]
Closing this. Just had to install the dependencies

**Comment by kporras07** [comment]
Thanks!

For history purposes, I think this was the same than #443 and it worked the second time because you used a simpler password.

This was fixed and merged to the main branch recently but a release is still pending to be created

**Comment by jahzlariosa** [comment]
Thanks @kporras07
