### ISSUE TITLE
build-env:create-project permission denied on Windows 10

### ISSUE THREAD

**Issue by jraviotta** [pantheon-systems/terminus-build-tools-plugin#71]
FYI I replaced personal output with variables in <> below.

Using git bash on Windows 10

`terminus build-env:create-project --team="<team>" --org="<org>" d7==stability="dev" <target>`

 ```
Enter the password you would like to use to log in to your test site,
 or leave empty for a random password::
 >

 [notice] Create GitHub project <org>/<target> from pantheon-systems/example-drops-7-composer
 [notice] Creating project and resolving dependencies.
 [notice] Running composer create-project --working-dir=<%USERPROFILE%>\AppData\Local\Temp\locABE4.tmp pantheon-systems/example-drops-7-composer <target> -n --stability dev
Installing pantheon-systems/example-drops-7-composer (dev-master 7f32ea0ec2da2f8dfde152718b1237d55b3863bc)
  - Installing pantheon-systems/example-drops-7-composer (dev-master master): Cloning master from cache
Created project in <target>
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 75 installs, 0 updates, 0 removals
  - Installing cweagans/composer-patches (1.6.1): Loading from cache
  - Installing derhasi/composer-preserve-paths (0.1.4): Loading from cache


  [ErrorException]
  chmod(): Permission denied


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--
ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]
```

The command almost works when running git bash as an admin.

```
[error]  Command `git -C C:\Users\jraviotta\AppData\Local\Temp\loc9EAD.tmp/4PillarsTrans commit -m 'Initial commit'` failed with exit code 1
PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "C:\Users\jraviotta\AppData\Local\Temp\loc9EAD.tmp\4PillarsTrans\.git\objects\fe\1729825ba5e464f242b8ee4d1bb7d057e36754": unlink(C:\Users\jraviotta\AppData\Loca
l\Temp\loc9EAD.tmp\4PillarsTrans\.git\objects\fe\1729825ba5e464f242b8ee4d1bb7d057e36754): Permission denied. in C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php:180
Stack trace:
#0 C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#4 C:\Users\jraviotta\PortableNix\ve in C:\Users\jraviotta\PortableNix\vendor\symfony\filesystem\Filesystem.php on line 180

Fatal error: Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to remove file "<%USERPROFILE%>\AppData\Local\Temp\loc9EAD.tmp\<target>\.git\objects\fe\1729825ba5e464f242b8ee4d1bb7d057e36754": unlink(<%USERPROFILE%>\AppData\Local\Tem
p\loc9EAD.tmp\<target>\.git\objects\fe\1729825ba5e464f242b8ee4d1bb7d057e36754): Permission denied. in <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php:180
Stack trace:
#0 <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#1 <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#2 <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#3 <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php(172): Symfony\Component\Filesystem\Filesystem->remove(Array)
#4 <%USERPROFILE%>\PortableNix\ve in <%USERPROFILE%>\PortableNix\vendor\symfony\filesystem\Filesystem.php on line 180

```

**Comment by jraviotta** [comment]
Same result with 

`terminus build-env:create-project --team="<team>" --org="<org>" d8 <target>`

**Comment by dchaffin** [comment]
Any updates on this?

**Comment by jraviotta** [comment]
@greg-1-Anderson is this related to https://github.com/pantheon-systems/example-drops-8-composer/pull/143?

**Comment by ataylorme** [comment]
Cleaning up old issues. Terminus itself does not support Windows therefore we cannot support Windows in a Terminus plugin
